[package]
name = "rustboot"
version = "0.1.0"
authors = ["Adam Young <ayoung@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
